# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ubuntu16-04"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.provision "shell", path: "../common-deb/provision.sh"

  config.vm.provision "shell", path: "../common-deb/provision_user.sh", privileged: false

  config.vm.provision "shell", path: "../common/install_singularity.sh", privileged: false
  
  config.vm.synced_folder "~/Git/", "/Git", type: "nfs", nfs_udp: false

end
