# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.provision "shell", path: "../common-rpm/provision.sh"

  config.vm.provision "shell", path: "../common-rpm/provision_user.sh", privileged: false

  config.vm.provision "file", source: "~/.gitconfig", destination: "$HOME/.gitconfig"

  config.vm.synced_folder "~/Git/", "/Git", type: "nfs", nfs_version: 4, nfs_udp: false

end
